# Site settings
title: Private Method
header-img: img/home-bg.jpg
email: david.ko@damncarousel.com
copyright_name:
description: "Word"
baseurl: ""
url: "http://nycdavid.github.io"
twitter_username:
github_username: nycdavid
facebook_username:
email_username: david.ko@damncarousel.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
