baseURL = "https://www.velvetreactor.com/"
languageCode = "en-us"
title = "Words"
theme = "engimo"
disqusShortname = "redvelvet-1"
googleAnalytics = "UA-111421177-1"
pygmentsStyle = "solarized-light"

[params]
    author = "David Ko"
    description = "Computer words"
    githubUsername = "velvetreactor"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    highlight = true
    highlightStyle = "solarized-light"
    highlightLanguages = ["go", "ruby", "javascript"]

[params.sidebar]
    enable = true
[params.widgets]
    sidebar = ["about", "search"]
[parmas.w]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:david.ko@velvetreactor.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/velvetreactor/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/davidsjko/"
    name = "linkedin"
    weight = 3

[[permalinks]]
    post = "/engineering-records/:title/"
